name: Nightly Release

permissions: {}

on:
  push:
    branches:
      - main

jobs:
  delete_tag:
    permissions:
      contents: write # required to delete the existing nightly release/tag
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Delete release
        uses: dev-drprasad/delete-tag-and-release@5eafd8668311bf3e4d6c1e9898f32a317103de68 #v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete_release: true
          tag_name: 2.0.0-nightly
  nightly:
    needs: delete_tag
    permissions:
      contents: write # required by the called release workflow to create tags and releases
      id-token: write # required by the called release workflow to assume the AWS release role
    uses: Checkmarx/ast-cli/.github/workflows/release.yml@79eed8cf802a4b8a43e5c7c43d000df3b39bd323 # main
    with:
      tag: "2.0.0-nightly"
    secrets: inherit
